
export const dataList = [
    {
      id: 1,
      propertyType: 'Pet Friendly',
      price: 800,
      beds: 1,
      baths: 1,
      area: 512 ,
      state:"New York" ,
      location: "515 Montgometry St New York",
      moveIn :new  Date("10,04,2022"),
      coverSrc: '/images/frien1.webp',
    },
    {
      id: 2,
      propertyType: 'Pet Friendly',
      price: 1500,
      beds: 1,
      baths: 2,
      area: 730,
      state:"Savannah, GA" ,
      location: "1565 Benton Blvd Savannah, GA" ,
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/friend2.webp',
    },
    {
      id: 3,
      propertyType: 'Pet Friendly',
      price: 3300,
      beds: 3,
      baths: 4,
      area:1200,
      state:"Callifornia" ,
      location: "630 Indian st, Callifornia",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/friend3.webp',
    },
    {
      id: 4,
      propertyType: 'With Pool',

      price: 3000,
      beds: 2,
      baths: 2,
      area: 1500,
      state:"New York" ,
      location:"1565 Benton Blvd, New York" ,
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/pool1.webp',
    },
    {
      id: 5,
      propertyType: 'With Pool',
      price: 1500,
      beds:1 ,
      baths: 1,
      area: 1000,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,25,2022"),
      coverSrc: '/images/poolI.webp',
    },
    {
      id: 6,
      propertyType: 'With Pool',
      price: 3000,
      beds: 2 ,
      baths:4 ,
      area: 2200,
      state:"Callifornia" ,
      location: "102 E Liberty St Callifornia",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/poolIV.webp',
    },
    {
      id: 7,      
      propertyType: 'In-unit laundary',

      price: 2200,
      beds:2 ,
      baths: 2,
      area:1000 ,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/Inunit1.webp',
    },
    {
      id: 8,      
      propertyType: 'In-unit laundary',
      price: 1500,
      beds: 1,
      baths: 1,
      area: 730,
      state:"Callifornia" ,
      location: "102 E Liberty St Callifornia",
      moveIn:new Date("10/30/2022") ,  //Can not move in
      coverSrc: '/images/inunit2.webp',
    },
    {
      id: 9,
      propertyType: 'In-unit laundary',
      price: 3000,
      beds:2 ,
      baths: 3,
      area: 1500,
      state:"New York" ,
      location:"1565 Benton Blvd, New York" ,
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/Inunit3.webp',
    },
    {
      id: 10,      
      propertyType: 'Studio Appartment',

      price: 3000,
      beds: 2,
      baths: 4,
      area: 1500,
      state:"Savannah, GA" ,
      location: "1512 Bull St Savannah, GA",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/Std1.webp',
    },
    {
      id: 11,      
      propertyType: 'Studio Appartment',
      price: 1500,
      beds: 1,
      baths: 2,
      area: 1000,
      state:"New York" ,
      location: "1565 Benton Blvd, New York",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/std2.webp',
    },
    {
      id: 12,      
      propertyType: 'Studio Appartment',
      price: 3000,
      beds: 2,
      baths: 3,
      area: 1500,
      state:"Callifornia" ,
      location: "3 Woodcock Rd Callifornia",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/std3.webp',
    },
    {
      id: 13,
      propertyType: 'Pet Friendly',
      price: 1500,
      beds: 2,
      baths: 1,
      area: 512 ,
      state:"New York" ,
      location: "515 Montgometry St New York",
      moveIn :new  Date("10,21,2022"),
      coverSrc: '/images/frien1.webp',
    },
    {
      id: 14,
      propertyType: 'With Pool',

      price: 3000,
      beds: 3,
      baths: 3,
      area: 1500,
      state:"New York" ,
      location:"1565 Benton Blvd, New York" ,
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/pool1.webp',
    },
    {
      id: 15,      
      propertyType: 'In-unit laundary',

      price: 1000,
      beds:1 ,
      baths: 2,
      area:1000 ,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/Inunit1.webp',
    },
    {
      id: 16,
      propertyType: 'Pet Friendly',
      price: 3000,
      beds: 3,
      baths: 3,
      area: 1512 ,
      state:"New York" ,
      location: "515 Montgometry St New York",
      moveIn :new  Date("10,21,2022"),
      coverSrc: '/images/frien1.webp',
    },
    {
      id: 17,
      propertyType: 'In-unit laundary',
      price: 3000,
      beds:2 ,
      baths: 2,
      area: 1500,
      state:"New York" ,
      location:"1565 Benton Blvd, New York" ,
      moveIn:new  Date("10,28,2022"),
      coverSrc: '/images/Inunit3.webp',
    },
    
    {
      id: 18,      
      propertyType: 'Studio Appartment',
      price: 3000,
      beds: 2,
      baths: 2,
      area: 1200,
      state:"New York" ,
      location: "1565 Benton Blvd, New York",
      moveIn:new  Date("10,30,2022"),
      coverSrc: '/images/std2.webp',
    },
    {
      id: 19,
      propertyType: 'With Pool',

      price: 3000,
      beds: 3,
      baths: 3,
      area: 1500,
      state:"New York" ,
      location:"1565 Benton Blvd, New York" ,
      moveIn:new  Date("11,04,2022"),
      coverSrc: '/images/pool1.webp',
    },
    {
      id: 20,
      propertyType: 'Pet Friendly',
      price: 1500,
      beds: 2,
      baths: 1,
      area:1200,
      state:"Callifornia" ,
      location: "630 Indian st, Callifornia",
      moveIn:new  Date("10,23,2022"),
      coverSrc: '/images/friend3.webp',
    },
    {
      id: 21,
      propertyType: 'With Pool',
      price: 3000,
      beds: 2 ,
      baths:4 ,
      area: 2200,
      state:"Callifornia" ,
      location: "102 E Liberty St Callifornia",
      moveIn:new  Date("10,31,2022"),
      coverSrc: '/images/poolIV.webp',
    },
    {
      id: 22,
      propertyType: 'Pet Friendly',
      price: 3000,
      beds: 2,
      baths: 1,
      area:1200,
      state:"Callifornia" ,
      location: "630 Indian st, Callifornia",
      moveIn:new  Date("10,23,2022"),
      coverSrc: '/images/friend3.webp',
    },
    {
      id: 23,
      propertyType: 'Pet Friendly',
      price: 1500,
      beds: 1,
      baths: 1,
      area:1000,
      state:"Callifornia" ,
      location: "630 Indian st, Callifornia",
      moveIn:new  Date("10,10,2022"),
      coverSrc: '/images/friend3.webp',
    },
    {
      id: 24,
      propertyType: 'In-unit laundary',
      price: 3000,
      beds: 3,
      baths: 3,
      area: 1512 ,
      state:"Callifornia" ,
      location: "102 E Liberty St Callifornia",
      moveIn :new  Date("10,28,2022"),
      coverSrc: '/images/frien1.webp',
    },
    {
      id: 25,
      propertyType: 'In-unit laundary',
      price: 1500,
      beds: 1,
      baths: 2,
      area: 1512 ,
      state:"Callifornia" ,
      location: "102 E Liberty St Callifornia",
      moveIn :new  Date("10,03,2022"),
      coverSrc: '/images/frien1.webp',
    },
    {
      id: 26,
      propertyType: 'In-unit laundary',
      price:3000,
      beds: 3,
      baths: 2,
      area: 1512 ,
      state:"Callifornia" ,
      location: "102 E Liberty St Callifornia",
      moveIn :new  Date("10,03,2022"),
      coverSrc: '/images/frien1.webp',
    },
    {
      id: 27,      
      propertyType: 'Studio Appartment',
      price: 3000,
      beds: 2,
      baths: 3,
      area: 1500,
      state:"Callifornia" ,
      location: "3 Woodcock Rd Callifornia",
      moveIn:new  Date("10,26,2022"),
      coverSrc: '/images/std3.webp',
    },
    {
      id: 28,
      propertyType: 'Pet Friendly',
      price: 3000,
      beds: 3,
      baths: 4,
      area: 730,
      state:"Savannah, GA" ,
      location: "1565 Benton Blvd Savannah, GA" ,
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/friend2.webp',
    },
    {
      id: 29,      
      propertyType: 'In-unit laundary',

      price: 1500,
      beds:1 ,
      baths: 2,
      area:1000 ,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/Inunit1.webp',
    },
    {
      id: 30,      
      propertyType: 'Studio Appartment',

      price: 1500,
      beds: 1,
      baths: 2,
      area: 1500,
      state:"Savannah, GA" ,
      location: "1512 Bull St Savannah, GA",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/Std1.webp',
    },
    {
      id: 31,
      propertyType: 'Pet Friendly',
      price: 1500,
      beds: 1,
      baths: 2,
      area: 730,
      state:"Savannah, GA" ,
      location: "1565 Benton Blvd Savannah, GA" ,
      moveIn:new  Date("10,27,2022"),
      coverSrc: '/images/friend2.webp',
    },
    {
      id: 32,      
      propertyType: 'In-unit laundary',

      price: 3000,
      beds:3 ,
      baths: 3,
      area:1000 ,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/Inunit1.webp',
    },
    {
      id: 33,
      propertyType: 'Pet Friendly',
      price: 3000,
      beds: 4,
      baths: 2,
      area: 730,
      state:"Savannah, GA" ,
      location: "1565 Benton Blvd Savannah, GA" ,
      moveIn:new  Date("10,24,2022"),
      coverSrc: '/images/friend2.webp',
    },
    {
      id: 34,
      propertyType: 'With Pool',
      price: 1500,
      beds:1 ,
      baths: 1,
      area: 1000,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,16,2022"),
      coverSrc: '/images/poolI.webp',
    },
    {
      id: 35,      
      propertyType: 'Studio Appartment',

      price: 1500,
      beds: 1,
      baths: 2,
      area: 1500,
      state:"Savannah, GA" ,
      location: "1512 Bull St Savannah, GA",
      moveIn:new  Date("10,24,2022"),
      coverSrc: '/images/Std1.webp',
    },
    {
      id: 36,
      propertyType: 'With Pool',
      price: 3000,
      beds:3 ,
      baths: 2,
      area: 1000,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,13,2022"),
      coverSrc: '/images/poolI.webp',
    },
    {
      id: 37,      
      propertyType: 'In-unit laundary',

      price: 3000,
      beds:3 ,
      baths: 3,
      area:1000 ,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,27,2022"),
      coverSrc: '/images/Inunit1.webp',
    },
    {
      id: 38,      
      propertyType: 'Studio Appartment',

      price: 3000,
      beds: 3,
      baths: 2,
      area: 1500,
      state:"Savannah, GA" ,
      location: "1512 Bull St Savannah, GA",
      moveIn:new  Date("10,04,2022"),
      coverSrc: '/images/Std1.webp',
    },
    {
      id: 39,      
      propertyType: 'In-unit laundary',

      price: 1500,
      beds:1 ,
      baths: 3,
      area:1000 ,
      state:"Savannah, GA" ,
      location: "1475 Chatham Pkwy Savannah, GA",
      moveIn:new  Date("10,28,2022"),
      coverSrc: '/images/Inunit1.webp',
    },

  ];